airflow_compose := "compose/local/airflow/docker-compose.yaml"
dev_compose := "compose/local/docker-compose.yaml"
realtime_compose := "compose/local/realtime/docker-compose.yaml"
realtime_prod_compose := "compose/prod/docker-compose.yaml"

# Application PostgreSQL, Redis and Grafana.
dev:
    docker compose -f {{dev_compose}} up -d

dev-down:
    docker compose -f {{dev_compose}} down

# Airflow plus the application services it depends on.
airflow:
    docker compose -f {{airflow_compose}} build
    docker compose -f {{airflow_compose}} up -d airflow-init
    docker compose -f {{airflow_compose}} up -d

airflow-down:
    docker compose -f {{airflow_compose}} down

# KIS 실시간 WebSocket 수집기(개발). `just dev`의 DB(15432)가 먼저 떠 있어야 한다.
realtime:
    docker compose -f {{realtime_compose}} build
    docker compose -f {{realtime_compose}} up -d

realtime-down:
    docker compose -f {{realtime_compose}} down

# KIS 실시간 WebSocket 수집기(운영). 운영 호스트에서 실행하며 운영 DB를 본다.
realtime-prod:
    docker compose -f {{realtime_prod_compose}} build
    docker compose -f {{realtime_prod_compose}} up -d

realtime-prod-down:
    docker compose -f {{realtime_prod_compose}} down

# 운영 배포. NAS clone(/volume1/docker/finance)에서 git pull 후 그 안에서 실행한다.
# compose·Dockerfile·requirements 변경은 up -d --build가 스스로 재생성하고,
# bind-mount 코드(apps/)는 up이 감지 못 하므로 realtime은 무조건 재시작한다.
# 열린 분은 원래 저장하지 않고 마감 후 REST가 확정본을 채우므로 몇 초 끊김만 비용이다.
# airflow는 재시작 불필요 — dags/modules는 dag-processor가 재파싱한다.
# airflow/airflow.cfg 변경만 수동 스택 재시작이 필요하다(README 배포 절).
deploy:
    docker compose -f compose/prod/airflow/docker-compose.yaml up -d --build
    docker compose -f compose/prod/docker-compose.yaml up -d --build
    docker compose -f compose/prod/docker-compose.yaml restart

# Run an Alembic command across every migration-enabled database alias.
# Example: `just migrate upgrade head`.
migrate +args:
    uv run python -m migrations.cli {{args}}

# New autogenerated revision with one section per database alias.
# Example: `just makemigrations "create market tables"`.
makemigrations message:
    uv run python -m migrations.cli revision --autogenerate -m "{{message}}"

# Join every open head into one revision. Needed after two branches each added
# a revision on top of the same parent, which makes `head` ambiguous.
# Example: `just mergemigrations "merge jgb seed into quote symbol chain"`.
mergemigrations message:
    uv run python -m migrations.cli merge -m "{{message}}"

# New Fernet key for compose/local/airflow/.env.
fernet:
    uv run --quiet --no-project --with cryptography python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
