set shell := ["powershell", "-NoLogo", "-NoProfile", "-Command"]

airflow_compose := "compose/local/airflow/docker-compose.yaml"
dev_compose := "compose/local/docker-compose.yaml"

# Application PostgreSQL, Redis and Grafana.
dev:
    docker compose -f {{dev_compose}} up -d

dev-down:
    docker compose -f {{dev_compose}} down

# Airflow plus the application services it depends on.
airflow:
    docker compose -f {{airflow_compose}} build
    docker compose -f {{airflow_compose}} up -d airflow-init
    docker compose -f {{airflow_compose}} up -d

airflow-down:
    docker compose -f {{airflow_compose}} down

# Run an Alembic command across every migration-enabled database alias.
# Example: `just migrate upgrade head`.
migrate +args:
    uv run python -m migrations.cli {{args}}

# New autogenerated revision with one section per database alias.
# Example: `just makemigrations "create market tables"`.
makemigrations message:
    uv run python -m migrations.cli revision --autogenerate -m "{{message}}"

# Join every open head into one revision. Needed after two branches each added
# a revision on top of the same parent, which makes `head` ambiguous.
# Example: `just mergemigrations "merge jgb seed into quote symbol chain"`.
mergemigrations message:
    uv run python -m migrations.cli merge -m "{{message}}"

# New Fernet key for compose/local/airflow/.env.
fernet:
    uv run --quiet --no-project --with cryptography python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
