apiVersion: 1

datasources:
  - name: news2
    uid: news2-postgres
    type: postgres
    access: proxy
    url: $NEWS_DB_URL
    database: $NEWS_DB_NAME
    user: $NEWS_DB_USER
    isDefault: true
    editable: false
    secureJsonData:
      password: $NEWS_DB_PASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      timescaledb: false
