"""create quote symbol master

Revision ID: 05fb2529386d
Revises: 9c1faba10bf1
Create Date: 2026-08-08 15:56:10.926669

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05fb2529386d"
down_revision: str | Sequence[str] | None = "9c1faba10bf1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# 지금 수집 중인 심볼의 시드. 이 목록은 이 리비전이 만들어진 시점의 값으로 고정한다.
# 심볼을 늘리면 수집기 Enum과 함께 새 리비전에서 INSERT를 추가한다. 여기서 앱 코드를
# import해 오면 나중에 Enum이 바뀔 때 과거 리비전의 결과가 따라 바뀐다.
#
# (provider, symbol, kind, country, country_name, label)
SEED: tuple[tuple[str, str, str, str, str, str], ...] = (
    ("yahoo", "SP500_FUT", "index_future", "US", "미국", "S&P500 선물"),
    ("yahoo", "NASDAQ100_FUT", "index_future", "US", "미국", "나스닥100 선물"),
    # VIX는 지수이지만 변동성 지수라 정상 변동폭이 다른 지수의 열 배쯤 된다. 같은 축에
    # 겹치면 나머지가 납작해지므로 대시보드에서 기본 선택에서 빼 둔다.
    ("yahoo", "VIX", "index", "US", "미국", "VIX 변동성 지수"),
    ("yahoo", "SOX", "index", "US", "미국", "필라델피아 반도체 지수"),
    ("yahoo", "KOSPI", "index", "KR", "한국", "코스피"),
)


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    quote_symbol = op.create_table(
        "quote_symbol",
        sa.Column(
            "provider",
            sa.Text(),
            nullable=False,
            comment="데이터 제공처 식별자(예: yahoo). quote_bar.provider와 같은 값이다",
        ),
        sa.Column(
            "symbol",
            sa.Text(),
            nullable=False,
            comment="제공처 안에서 심볼을 가리키는 식별자. quote_bar.symbol과 같은 값이다",
        ),
        sa.Column(
            "kind",
            sa.Enum("index", "index_future", name="quotesymbolkind", native_enum=False, length=20),
            nullable=False,
            comment="현물 지수(index)인지 지수선물(index_future)인지. 거래 시간대가 달라 화면을 가른다",
        ),
        sa.Column("country", sa.Text(), nullable=False, comment="기초 시장의 국가(ISO 3166-1 alpha-2, 예: US 또는 KR)"),
        sa.Column(
            "country_name",
            sa.Text(),
            nullable=False,
            comment="국가 표시 이름. 국가에 붙는 속성이 더 늘면 country 마스터 테이블로 분리한다",
        ),
        sa.Column("label", sa.Text(), nullable=False, comment="차트와 표에 쓰는 표시 이름(예: 나스닥100 선물)"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.CheckConstraint("kind IN ('index', 'index_future')", name="ck_quote_symbol_kind"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "symbol", name="uq_quote_symbol_natural_key"),
        comment="quote_bar 심볼이 현물 지수인지 지수선물인지 설명하는 마스터",
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        quote_symbol,
        [
            {
                "provider": provider,
                "symbol": symbol,
                "kind": kind,
                "country": country,
                "country_name": country_name,
                "label": label,
            }
            for provider, symbol, kind, country, country_name, label in SEED
        ],
        # offline(`--sql`)에서는 executemany를 찍을 수 없다. 행마다 INSERT를 내게 한다.
        multiinsert=False,
    )


def downgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quote_symbol")
    # ### end Alembic commands ###


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
