"""add daily ohlc to stock investor trade

Revision ID: 0efdb0dd4485
Revises: cf8fd4e2b84e
Create Date: 2026-08-14 17:56:34.584617

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0efdb0dd4485'
down_revision: str | Sequence[str] | None = 'cf8fd4e2b84e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # 이미 행이 있는 테이블에 NOT NULL 컬럼을 붙인다. 기본값 없이는 ALTER 가 거부되므로
    # 0 을 임시로 채운 뒤 기본값만 떼어 낸다. 남은 0 은 재수집이 덮는다. 같은 응답에 이미
    # 있던 값이라 호출은 늘지 않는다.
    for name, comment in (
        ("open_price", "시가(stck_oprc). 단위는 원"),
        ("high_price", "고가(stck_hgpr). 단위는 원"),
        ("low_price", "저가(stck_lwpr). 단위는 원"),
    ):
        op.add_column(
            "stock_investor_trade_daily",
            sa.Column(
                name,
                sa.Numeric(precision=18, scale=4),
                nullable=False,
                server_default=sa.text("0"),
                comment=comment,
            ),
        )
        op.alter_column("stock_investor_trade_daily", name, server_default=None)


def downgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_investor_trade_daily', 'low_price')
    op.drop_column('stock_investor_trade_daily', 'high_price')
    op.drop_column('stock_investor_trade_daily', 'open_price')
    # ### end Alembic commands ###


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

