"""add fx and rate kinds with new symbols

Revision ID: 0ff0870a71fb
Revises: 3bf637f8ff6b
Create Date: 2026-08-08 18:22:05.091901

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ff0870a71fb"
down_revision: str | Sequence[str] | None = "3bf637f8ff6b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


# 새로 붙이는 심볼. (provider, symbol, kind, country, country_name, label)
#
# `kind` 에 `fx` 와 `rate` 가 처음 들어온다. 환율과 금리는 지수와 정상 변동폭의 자릿수가
# 달라서 같은 화면에 두면 읽을 수 없다. 특히 금리는 변화율(%)이 아니라 bp 로 읽는 값이다.
#
# 환율의 `country` 는 USD 가 아닌 쪽의 국가로 둔다. 달러인덱스는 달러 자체를 재는 지수라 US 다.
SEED: tuple[tuple[str, str, str, str, str, str], ...] = (
    # 코스피200 선물의 기초지수. 이게 있어야 베이시스를 낼 수 있다.
    ("kis", "KOSPI200", "index", "KR", "한국", "코스피200"),
    # 한국 정규장과 시간대가 겹치는 유일한 해외 현물.
    ("yahoo", "NIKKEI225", "index", "JP", "일본", "닛케이225"),
    ("yahoo", "TAIEX", "index", "TW", "대만", "대만 가권지수"),
    # FRED 는 하루 한 값이라 장중 금리 움직임을 못 본다.
    ("yahoo", "US10Y", "rate", "US", "미국", "미국 10년물 금리"),
    # 거의 24시간 움직여 한국 장중 구간을 채운다.
    ("yahoo", "USDKRW", "fx", "KR", "한국", "원/달러"),
    ("yahoo", "USDJPY", "fx", "JP", "일본", "엔/달러"),
    ("yahoo", "DXY", "fx", "US", "미국", "달러인덱스"),
)


def upgrade_default() -> None:
    # CHECK 제약은 값을 늘릴 때마다 다시 만들어야 한다. PostgreSQL native enum 을 쓰지 않는
    # 대신 치르는 비용이고, 대신 값 추가가 트랜잭션 안에서 끝난다.
    op.drop_constraint("ck_quote_symbol_kind", "quote_symbol", type_="check")
    op.create_check_constraint(
        "ck_quote_symbol_kind",
        "quote_symbol",
        "kind IN ('index', 'index_future', 'fx', 'rate')",
    )
    op.alter_column(
        "quote_symbol",
        "kind",
        existing_type=sa.VARCHAR(length=20),
        existing_nullable=False,
        comment=(
            "값의 종류(index, index_future, fx, rate). 화면을 가르는 기준이다. "
            "거래 시간대가 다르고 정상 변동폭의 자릿수도 달라 한 축에 겹치면 읽을 수 없다"
        ),
        existing_comment="현물 지수(index)인지 지수선물(index_future)인지. 거래 시간대가 달라 화면을 가른다",
    )

    for provider, symbol, kind, country, country_name, label in SEED:
        op.execute(
            sa.text(
                "INSERT INTO quote_symbol (provider, symbol, kind, country, country_name, label)"
                " VALUES (:provider, :symbol, :kind, :country, :country_name, :label)"
            ).bindparams(
                provider=provider,
                symbol=symbol,
                kind=kind,
                country=country,
                country_name=country_name,
                label=label,
            )
        )


def downgrade_default() -> None:
    for provider, symbol, *_ in SEED:
        op.execute(
            sa.text("DELETE FROM quote_bar WHERE provider = :provider AND symbol = :symbol").bindparams(
                provider=provider, symbol=symbol
            )
        )
        op.execute(
            sa.text("DELETE FROM quote_symbol WHERE provider = :provider AND symbol = :symbol").bindparams(
                provider=provider, symbol=symbol
            )
        )
    op.drop_constraint("ck_quote_symbol_kind", "quote_symbol", type_="check")
    op.create_check_constraint(
        "ck_quote_symbol_kind",
        "quote_symbol",
        "kind IN ('index', 'index_future')",
    )


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
