"""add contract code and seed kospi200 future

Revision ID: 2495c7a1c877
Revises: 05fb2529386d
Create Date: 2026-08-08 17:04:27.049868

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2495c7a1c877"
down_revision: str | Sequence[str] | None = "05fb2529386d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quote_bar",
        sa.Column(
            "contract_code",
            sa.Text(),
            nullable=True,
            comment="선물의 실제 월물 코드(예: A01609). 현물 지수와 연속 심볼은 NULL이다. 월물이 바뀌면 가격에 갭이 생기는데, 이 값이 없으면 그 갭이 시장 급변인지 롤오버인지 구분할 수 없다",
        ),
    )
    # ### end Alembic commands ###

    # KOSPI200 정규 선물을 마스터에 넣는다. Yahoo 에 없어서 KIS 로만 받을 수 있고
    # 국내 시세는 무료다. 미니(A056)가 아니라 정규(A016) 계약이다.
    op.execute(
        sa.text(
            "INSERT INTO quote_symbol (provider, symbol, kind, country, country_name, label)"
            " VALUES ('kis', 'KOSPI200_FUT', 'index_future', 'KR', '한국', '코스피200 선물')"
        )
    )


def downgrade_default() -> None:
    op.execute(sa.text("DELETE FROM quote_symbol WHERE provider = 'kis' AND symbol = 'KOSPI200_FUT'"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quote_bar", "contract_code")
    # ### end Alembic commands ###


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
