"""add document assessment and tag tables

Revision ID: 400f10fc8e60
Revises: 5e2f9e056cda
Create Date: 2026-08-15 12:25:48.539139

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "400f10fc8e60"
down_revision: str | Sequence[str] | None = "5e2f9e056cda"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_indicator",
        sa.Column(
            "document_id", sa.BigInteger(), nullable=False, comment="문서 ID. 문서가 지워지면 태그도 함께 지운다"
        ),
        sa.Column(
            "provider",
            sa.Text(),
            nullable=False,
            comment="지표 제공처(fred, ecos, yahoo 등). series_id는 제공처 안에서만 고유하다",
        ),
        sa.Column(
            "series_id",
            sa.Text(),
            nullable=False,
            comment="indicator_series.series_id 또는 quote_symbol.symbol과 같은 값(예: DGS10, USDKRW)",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "provider", "series_id", name="uq_document_indicator_natural_key"),
        comment="문서와 지표 시계열을 잇는 태그 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index("ix_document_indicator_series", "document_indicator", ["provider", "series_id"], unique=False)
    op.create_table(
        "document_instrument",
        sa.Column(
            "document_id", sa.BigInteger(), nullable=False, comment="문서 ID. 문서가 지워지면 태그도 함께 지운다"
        ),
        sa.Column(
            "ticker",
            sa.Text(),
            nullable=False,
            comment="instrument.ticker와 같은 값(예: 005930). 외래키를 걸지 않아 마스터가 없어도 태깅이 멈추지 않는다",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "ticker", name="uq_document_instrument_natural_key"),
        comment="문서와 추적 종목을 잇는 태그 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index("ix_document_instrument_ticker", "document_instrument", ["ticker"], unique=False)
    op.add_column(
        "document",
        sa.Column(
            "direction",
            sa.Enum("positive", "negative", "neutral", name="direction", native_enum=False, length=20),
            nullable=True,
            comment="LLM이 본 방향(positive, negative 또는 neutral). 평가 전이면 NULL이다",
        ),
    )
    op.add_column(
        "document",
        sa.Column(
            "value_score",
            sa.Integer(),
            nullable=True,
            comment="관련성·새로움·구체성·영향의 0~2점 합계(0~8). **이 값으로 문서를 버리지 않는다.** 리포트를 만들 때 프롬프트가 상위 몇 개를 고르는 데만 쓴다",
        ),
    )
    op.add_column(
        "document",
        sa.Column(
            "assessment",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="LLM 응답 전체(세부 점수, 주제, 새 사실, 판단 근거, 근거 청크). 조회 조건이 굳으면 컬럼으로 뺀다",
        ),
    )
    op.add_column("document", sa.Column("llm_model", sa.Text(), nullable=True, comment="평가에 쓴 모델 이름"))
    op.add_column(
        "document",
        sa.Column(
            "prompt_version",
            sa.Text(),
            nullable=True,
            comment="평가에 쓴 프롬프트 버전. 이 값이 오르면 재평가 대상이 된다",
        ),
    )
    op.add_column(
        "document",
        sa.Column(
            "assessed_content_hash",
            sa.Text(),
            nullable=True,
            comment="평가 시점의 content_hash. 현재 content_hash와 다르면 본문이 바뀐 것이라 다시 평가한다. 이 컬럼이 없으면 같은 문서를 매번 다시 평가하거나 영영 안 하거나 둘 중 하나가 된다",
        ),
    )
    op.add_column(
        "document",
        sa.Column(
            "assessed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="평가를 마친 시각(UTC). 실패하면 NULL로 남아 다음 실행이 다시 집는다",
        ),
    )
    # ### end Alembic commands ###


def downgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "assessed_at")
    op.drop_column("document", "assessed_content_hash")
    op.drop_column("document", "prompt_version")
    op.drop_column("document", "llm_model")
    op.drop_column("document", "assessment")
    op.drop_column("document", "value_score")
    op.drop_column("document", "direction")
    op.drop_index("ix_document_instrument_ticker", table_name="document_instrument")
    op.drop_table("document_instrument")
    op.drop_index("ix_document_indicator_series", table_name="document_indicator")
    op.drop_table("document_indicator")
    # ### end Alembic commands ###


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
