"""add tier2 symbols with commodity bond equity kinds

Revision ID: 48eb0cf0a589
Revises: 0ff0870a71fb
Create Date: 2026-08-08 18:56:21.387333

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48eb0cf0a589"
down_revision: str | Sequence[str] | None = "0ff0870a71fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


KINDS_BEFORE = "kind IN ('index', 'index_future', 'fx', 'rate')"
KINDS_AFTER = "kind IN ('index', 'index_future', 'fx', 'rate', 'bond_future', 'commodity', 'equity')"

# 2순위 심볼. (provider, symbol, kind, country, country_name, label)
#
# `kind` 가 셋 늘어난다. 성격이 다른 값을 한 축에 겹치면 읽을 수 없기 때문이다.
#
# - `bond_future` 를 `rate` 와 나눈 이유는 **하나는 수익률이고 하나는 가격**이라서다.
#   `US10Y` 는 4.66(%)이고 `US10Y_FUT` 는 110(달러)이며 서로 반대로 움직인다.
#   같은 "미 10년물"이라 한 패널에 겹치면 읽는 사람이 반드시 틀린다.
# - `commodity` 와 `equity` 도 각자 정상 변동폭이 달라 따로 둔다.
SEED: tuple[tuple[str, str, str, str, str, str], ...] = (
    # 중화권·소형주. 한국 장중과 겹치는 아시아 심리 지표를 넓힌다.
    ("yahoo", "HSI", "index", "HK", "홍콩", "항셍"),
    ("yahoo", "SSE_COMP", "index", "CN", "중국", "상하이종합"),
    ("yahoo", "RUSSELL2000", "index", "US", "미국", "러셀2000"),
    # 역외 위안은 시장 스트레스를 본토보다 빨리 반영한다.
    ("yahoo", "USDCNH", "fx", "CN", "중국", "위안/달러(역외)"),
    ("yahoo", "JPYKRW", "fx", "KR", "한국", "원/엔"),
    # 아시아 세션에 살아 있는 유일한 미 금리 신호다. US10Y(수익률)는 미국 정규장만 움직인다.
    ("yahoo", "US10Y_FUT", "bond_future", "US", "미국", "미 10년 국채선물"),
    ("yahoo", "GOLD", "commodity", "US", "미국", "금"),
    ("yahoo", "SILVER", "commodity", "US", "미국", "은"),
    ("yahoo", "COPPER", "commodity", "US", "미국", "구리"),
    ("yahoo", "WTI", "commodity", "US", "미국", "WTI 원유"),
    # 반도체 공급망 참조가. 시그널 대상이 아니라 맥락용이다.
    ("yahoo", "TSMC_ADR", "equity", "TW", "대만", "TSMC ADR"),
    # 코스피와 같은 업종 분봉 경로라 추가 비용이 없다.
    ("kis", "KOSDAQ", "index", "KR", "한국", "코스닥"),
)


def _reset_kind_check(definition: str) -> None:
    op.drop_constraint("ck_quote_symbol_kind", "quote_symbol", type_="check")
    op.create_check_constraint("ck_quote_symbol_kind", "quote_symbol", definition)


def upgrade_default() -> None:
    _reset_kind_check(KINDS_AFTER)
    op.alter_column(
        "quote_symbol",
        "kind",
        existing_type=sa.VARCHAR(length=20),
        existing_nullable=False,
        comment=(
            "값의 종류(index, index_future, fx, rate, bond_future, commodity, equity). "
            "화면을 가르는 기준이다. 거래 시간대가 다르고 정상 변동폭의 자릿수도 달라 "
            "한 축에 겹치면 읽을 수 없다"
        ),
    )

    for provider, symbol, kind, country, country_name, label in SEED:
        op.execute(
            sa.text(
                "INSERT INTO quote_symbol (provider, symbol, kind, country, country_name, label)"
                " VALUES (:provider, :symbol, :kind, :country, :country_name, :label)"
            ).bindparams(
                provider=provider,
                symbol=symbol,
                kind=kind,
                country=country,
                country_name=country_name,
                label=label,
            )
        )


def downgrade_default() -> None:
    for provider, symbol, *_ in SEED:
        op.execute(
            sa.text("DELETE FROM quote_bar WHERE provider = :provider AND symbol = :symbol").bindparams(
                provider=provider, symbol=symbol
            )
        )
        op.execute(
            sa.text("DELETE FROM quote_symbol WHERE provider = :provider AND symbol = :symbol").bindparams(
                provider=provider, symbol=symbol
            )
        )
    _reset_kind_check(KINDS_BEFORE)


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
