"""create market_movement_snapshot table

Revision ID: 4bb73b5f30e0
Revises: 70d4f10af89d
Create Date: 2026-08-13 09:57:00.691305

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bb73b5f30e0"
down_revision: str | Sequence[str] | None = "70d4f10af89d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_movement_snapshot",
        sa.Column(
            "provider",
            sa.Text(),
            nullable=False,
            comment="데이터 제공처 식별자(kis). 같은 수집의 source_record.source와 같은 값이다",
        ),
        sa.Column(
            "symbol",
            sa.Enum("KOSPI", "KOSDAQ", name="movementmarket", native_enum=False, length=20),
            nullable=False,
            comment="분포를 고시한 지수(KOSPI, KOSDAQ). quote_bar.symbol과 같은 값이다",
        ),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="관측이 속한 1분의 시작 시각(UTC). REST는 응답을 받은 시각을 분 단위로 절삭한 값이라 제공처가 준 원천 시각이 아니다. 과거 분포를 복구하는 백필 값으로 쓰지 않는다",
        ),
        sa.Column(
            "upper_limit_count",
            sa.Integer(),
            nullable=False,
            comment="상한가 종목 수. 상승 종목 수 안에 포함된 부분집합이다(실측). 강조 표시용으로 따로 보존한다",
        ),
        sa.Column(
            "rising_count",
            sa.Integer(),
            nullable=False,
            comment="상승 종목 수. 상한가를 포함한다. 보합·하락과 더하면 그날 거래 종목 수가 된다",
        ),
        sa.Column("unchanged_count", sa.Integer(), nullable=False, comment="보합 종목 수"),
        sa.Column("falling_count", sa.Integer(), nullable=False, comment="하락 종목 수"),
        sa.Column(
            "lower_limit_count",
            sa.Integer(),
            nullable=False,
            comment="하한가 종목 수. 하락 종목 수에 포함되는지는 아직 확인하지 못했다(관측 내내 0이었다)",
        ),
        sa.Column(
            "source_record_id",
            sa.BigInteger(),
            nullable=False,
            comment="이 행을 마지막으로 갱신한 수집의 source_record 레코드 ID",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.CheckConstraint("symbol IN ('KOSPI', 'KOSDAQ')", name="ck_market_movement_snapshot_symbol"),
        sa.CheckConstraint(
            "upper_limit_count >= 0 AND rising_count >= 0 AND unchanged_count >= 0 AND falling_count >= 0 AND lower_limit_count >= 0",
            name="ck_market_movement_snapshot_counts_not_negative",
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "symbol", "observed_at", name="uq_market_movement_snapshot_natural_key"),
        comment="코스피·코스닥의 상승·보합·하락 종목 수를 분 단위로 누적하는 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index(
        "ix_market_movement_snapshot_source_record_id", "market_movement_snapshot", ["source_record_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_market_movement_snapshot_source_record_id", table_name="market_movement_snapshot")
    op.drop_table("market_movement_snapshot")
    # ### end Alembic commands ###


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
