"""create market_session table

Revision ID: 4c38c3f6a86a
Revises: 1f8d298bb5f4
Create Date: 2026-08-12 20:08:56.101256

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c38c3f6a86a"
down_revision: str | Sequence[str] | None = "1f8d298bb5f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_session",
        sa.Column(
            "market_code",
            sa.Enum("KRX", "US_EQUITY", name="marketcode", native_enum=False, length=20),
            nullable=False,
            comment="휴장 캘린더를 공유하는 시장 묶음(KRX, US_EQUITY). 상장 거래소를 뜻하는 Market enum과는 다른 체계다",
        ),
        sa.Column("market_name", sa.Text(), nullable=False, comment="사람이 읽는 시장 이름(예: 한국거래소)"),
        sa.Column(
            "country_code", sa.Text(), nullable=False, comment="시장이 속한 국가(ISO 3166-1 alpha-2, 예: KR 또는 US)"
        ),
        sa.Column(
            "session_date", sa.Date(), nullable=False, comment="그 시장의 현지 거래일. 시간대는 시장 현지 기준이다"
        ),
        sa.Column(
            "kis_weekday_code",
            sa.Text(),
            nullable=True,
            comment="국내 KIS 요일구분코드(wday_dvsn_cd). 미국 행은 NULL이다",
        ),
        sa.Column(
            "kis_business_day", sa.Boolean(), nullable=True, comment="국내 KIS 영업일 여부(bzdy_yn). 미국 행은 NULL이다"
        ),
        sa.Column(
            "kis_trading_day",
            sa.Boolean(),
            nullable=True,
            comment="국내 KIS 거래일 여부(tr_day_yn). 미국 행은 NULL이다",
        ),
        sa.Column(
            "kis_open_day",
            sa.Boolean(),
            nullable=True,
            comment="국내 KIS 개장일 여부(opnd_yn). 주문 가능 여부의 원본이다. 미국 행은 NULL이다",
        ),
        sa.Column(
            "kis_settlement_day",
            sa.Boolean(),
            nullable=True,
            comment="국내 KIS 결제일 여부(sttl_day_yn). 미국 행은 NULL이다",
        ),
        sa.Column(
            "local_settlement_date",
            sa.Date(),
            nullable=True,
            comment="해외 KIS 현지결제일자(acpl_sttl_dt). 국내 행은 NULL이다",
        ),
        sa.Column(
            "domestic_settlement_date",
            sa.Date(),
            nullable=True,
            comment="해외 KIS 국내결제일자(dmst_sttl_dt). 국내 행은 NULL이다",
        ),
        sa.Column(
            "effective_open_day",
            sa.Boolean(),
            nullable=True,
            comment="소비자가 쓰는 최종 개장일 판정. 조기 폐장일은 true다. 아직 판정하지 못한 날짜는 NULL이고, 이때 수집기는 시세 요청을 멈추지 않는다",
        ),
        sa.Column(
            "verified_by",
            sa.Enum("kis", "nyse", name="sessionverifier", native_enum=False, length=20),
            nullable=True,
            comment="effective_open_day를 채운 제공처(kis, nyse)",
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True, comment="최종 판정을 확인한 시각(UTC)"),
        sa.Column(
            "source_record_id",
            sa.BigInteger(),
            nullable=False,
            comment="이 행을 만든 수집의 source_record 레코드 ID. 국내는 KIS, 미국은 NYSE 수집이다",
        ),
        sa.Column(
            "verification_source_record_id",
            sa.BigInteger(),
            nullable=True,
            comment="같은 행을 보강한 다른 출처의 source_record 레코드 ID. 미국 행의 결제일을 채운 KIS 해외 수집이다",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.CheckConstraint("market_code IN ('KRX', 'US_EQUITY')", name="ck_market_session_market_code"),
        sa.CheckConstraint("verified_by IN ('kis', 'nyse')", name="ck_market_session_verified_by"),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["verification_source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_code", "session_date", name="uq_market_session_natural_key"),
        comment="시장별·날짜별 개장 여부와 결제일을 저장하는 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index("ix_market_session_session_date", "market_session", ["session_date"], unique=False)
    op.create_index("ix_market_session_source_record_id", "market_session", ["source_record_id"], unique=False)
    op.create_index(
        "ix_market_session_verification_source_record_id",
        "market_session",
        ["verification_source_record_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_market_session_verification_source_record_id", table_name="market_session")
    op.drop_index("ix_market_session_source_record_id", table_name="market_session")
    op.drop_index("ix_market_session_session_date", table_name="market_session")
    op.drop_table("market_session")
    # ### end Alembic commands ###


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
