"""create document tables

Revision ID: 5e2f9e056cda
Revises: e89bdfd17b06
Create Date: 2026-08-15 11:59:42.386008

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e2f9e056cda"
down_revision: str | Sequence[str] | None = "e89bdfd17b06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# 수집 출처 시드. 리비전에서 앱 코드를 import하지 않는다. import하면 나중에 수집기 Enum이
# 바뀔 때 과거 리비전의 결과가 따라 바뀐다. 대조는 tests/migrations가 한다.
#
# **여기 있는 피드는 전부 실제로 요청해 응답을 확인한 것이다**(2026-08-15). 설계 초안에 있던
# Reuters와 AP는 피드 도메인이 DNS에 없어 뺐다. 재정경제부·금융위원회·BIS·U.S. Treasury·KBS는
# 알려진 주소가 404 또는 503이라 주소를 다시 찾은 뒤 넣는다.
#
# `collection_mode`는 전부 `feed_content`로 시작한다. 원문 본문 추출을 아직 만들지 않았고,
# 이용조건 확인(`terms_checked_at`)도 하지 않아 `full_text`로 올릴 근거가 없다.
#
# (slug, name, source_kind, country, language, feed_url, collection_mode, enabled)
DOCUMENT_SOURCE_SEED: tuple[tuple[str, str, str, str | None, str, str, str, bool], ...] = (
    (
        "fed",
        "Federal Reserve",
        "official",
        "US",
        "en",
        "https://www.federalreserve.gov/feeds/press_all.xml",
        "feed_content",
        True,
    ),
    (
        "bls",
        "U.S. Bureau of Labor Statistics",
        "official",
        "US",
        "en",
        "https://www.bls.gov/feed/bls_latest.rss",
        "feed_content",
        True,
    ),
    (
        "bea",
        "U.S. Bureau of Economic Analysis",
        "official",
        "US",
        "en",
        "https://apps.bea.gov/rss/rss.xml",
        "feed_content",
        True,
    ),
    (
        "bok",
        "한국은행",
        "official",
        "KR",
        "ko",
        "https://www.bok.or.kr/portal/bbs/B0000338/news.rss?menuNo=200761",
        "feed_content",
        True,
    ),
    # SEC 최신 접수 목록은 전 종목 8-K가 시간당 수십 건씩 흐른다. 거시 문서 아카이브에
    # 넣으면 나머지 출처를 덮고 이후 LLM 태깅 비용도 여기서 대부분 나간다. 국내 종목 공시는
    # `dart_disclosure_intraday`가 이미 받고 있어 지금 켤 이유가 없다. 행은 남겨 둔다.
    (
        "sec",
        "SEC EDGAR 최신 접수",
        "official",
        "US",
        "en",
        "https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=8-K&output=atom",
        "feed_content",
        False,
    ),
    (
        "bbc_business",
        "BBC Business",
        "media",
        "GB",
        "en",
        "https://feeds.bbci.co.uk/news/business/rss.xml",
        "feed_content",
        True,
    ),
    (
        "cnbc",
        "CNBC",
        "media",
        "US",
        "en",
        "https://www.cnbc.com/id/100003114/device/rss/rss.html",
        "feed_content",
        True,
    ),
    (
        "npr_business",
        "NPR Business",
        "media",
        "US",
        "en",
        "https://feeds.npr.org/1006/rss.xml",
        "feed_content",
        True,
    ),
    (
        "yonhap",
        "연합뉴스 경제",
        "media",
        "KR",
        "ko",
        "https://www.yna.co.kr/rss/economy.xml",
        "feed_content",
        True,
    ),
)


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_source",
        sa.Column(
            "slug",
            sa.Text(),
            nullable=False,
            comment="출처 식별자(예: fed, yonhap). 수집기 Enum과 같은 값이며 document.source_slug가 이 값을 쓴다",
        ),
        sa.Column("name", sa.Text(), nullable=False, comment="출처 표시 이름"),
        sa.Column(
            "source_kind",
            sa.Enum("official", "media", name="sourcekind", native_enum=False, length=20),
            nullable=False,
            comment="출처 종류(official 또는 media). 공식기관 문서는 가치 점수와 무관하게 보관한다",
        ),
        sa.Column(
            "country", sa.Text(), nullable=True, comment="출처 국가(ISO 3166-1 alpha-2). BIS처럼 국제기구는 NULL이다"
        ),
        sa.Column(
            "language",
            sa.Text(),
            nullable=False,
            comment=(
                "이 출처가 쓰는 언어(ISO 639-1). 국가에서 추측하지 않고 출처마다 선언한다. "
                "한 출처가 여러 언어를 내보내면 그때 문서 단위 판별을 붙인다"
            ),
        ),
        sa.Column(
            "feed_url", sa.Text(), nullable=False, comment="발견 채널 URL(RSS 또는 Atom). 인증이 없어 그대로 저장한다"
        ),
        sa.Column(
            "collection_mode",
            sa.Enum("metadata_only", "feed_content", "full_text", name="collectionmode", native_enum=False, length=20),
            nullable=False,
            comment="어디까지 저장할지. metadata_only는 제목·URL만, feed_content는 피드가 준 요약까지, full_text는 원문 본문까지다. 이용조건에서 개인 자동수집이 확인된 출처만 full_text로 올린다",
        ),
        sa.Column("terms_url", sa.Text(), nullable=True, comment="이용조건 문서 URL"),
        sa.Column(
            "terms_checked_at",
            sa.Date(),
            nullable=True,
            comment="이용조건을 마지막으로 확인한 날짜(KST). collection_mode를 정한 근거 시점이다",
        ),
        sa.Column(
            "enabled",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="수집 대상 여부. 끄더라도 행은 남겨 왜 뺐는지를 보존한다",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.CheckConstraint(
            "collection_mode IN ('metadata_only', 'feed_content', 'full_text')",
            name="ck_document_source_collection_mode",
        ),
        sa.CheckConstraint("source_kind IN ('official', 'media')", name="ck_document_source_kind"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_document_source_slug"),
        comment="문서 수집 출처와 출처별 수집 정책을 보관하는 마스터",
        info={"database": "default", "managed": True},
    )
    op.create_table(
        "document",
        sa.Column(
            "source_slug",
            sa.Text(),
            nullable=False,
            comment="document_source.slug와 같은 값. 외래키를 걸지 않아 마스터가 없어도 수집이 멈추지 않는다",
        ),
        sa.Column(
            "external_id",
            sa.Text(),
            nullable=False,
            comment="출처 안에서 문서를 가리키는 식별자. 제공처 ID가 없으면 정규화한 URL을 쓴다",
        ),
        sa.Column("canonical_url", sa.Text(), nullable=False, comment="문서 원문 URL"),
        sa.Column(
            "document_type",
            sa.Enum("article", "report", "press_release", "speech", name="documenttype", native_enum=False, length=20),
            nullable=False,
            comment="문서 종류(article, report, press_release 또는 speech)",
        ),
        sa.Column("title", sa.Text(), nullable=False, comment="정규화한 제목"),
        sa.Column("summary", sa.Text(), nullable=True, comment="피드가 준 요약. 우리가 만든 요약이 아니다"),
        sa.Column(
            "body",
            sa.Text(),
            nullable=True,
            comment="정규화한 본문. metadata_only 출처는 NULL이며 CHECK 제약이 이를 강제한다",
        ),
        sa.Column(
            "language",
            sa.Text(),
            nullable=False,
            comment="본문 언어(ISO 639-1, 예: ko, en). 검색 토크나이저를 가르는 값이다",
        ),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="제공처가 알려 준 발행 시각(UTC). 피드가 주지 않으면 NULL이다",
        ),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="이 문서를 처음 본 시각(UTC). 발행 시각과 달리 항상 있다",
        ),
        sa.Column(
            "content_level",
            sa.Enum("metadata_only", "feed_content", "full_text", name="collectionmode", native_enum=False, length=20),
            nullable=False,
            comment="이 문서에 실제로 담긴 수준. 출처 정책과 같지만 본문 수집이 실패하면 낮아질 수 있다",
        ),
        sa.Column(
            "content_hash",
            sa.Text(),
            nullable=False,
            comment="정규화한 제목·요약·본문의 SHA-256. 재평가 여부와 완전 중복 판정의 기준이다. 정규화 규칙이 흔들리면 이 값이 매번 바뀌므로 규칙을 먼저 고정한다",
        ),
        sa.Column(
            "canonical_document_id",
            sa.BigInteger(),
            nullable=True,
            comment="중복일 때 대표 문서 ID. 대표 문서 자신은 NULL이다. 물리 삭제는 하지 않는다",
        ),
        sa.Column("source_record_id", sa.BigInteger(), nullable=False, comment="근거가 되는 source_record 레코드 ID"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.CheckConstraint(
            "content_level <> 'metadata_only' OR body IS NULL", name="ck_document_metadata_only_has_no_body"
        ),
        sa.CheckConstraint(
            "content_level IN ('metadata_only', 'feed_content', 'full_text')", name="ck_document_content_level"
        ),
        sa.CheckConstraint(
            "document_type IN ('article', 'report', 'press_release', 'speech')", name="ck_document_type"
        ),
        sa.ForeignKeyConstraint(["canonical_document_id"], ["document.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_slug", "external_id", name="uq_document_natural_key"),
        comment="수집한 경제 문서 한 건의 정규화 결과와 평가를 보관하는 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index("ix_document_canonical_document_id", "document", ["canonical_document_id"], unique=False)
    op.create_index("ix_document_content_hash", "document", ["content_hash"], unique=False)
    op.create_index("ix_document_published_at", "document", ["published_at"], unique=False)
    op.create_index("ix_document_source_record_id", "document", ["source_record_id"], unique=False)

    op.bulk_insert(
        sa.table(
            "document_source",
            sa.column("slug", sa.Text),
            sa.column("name", sa.Text),
            sa.column("source_kind", sa.String),
            sa.column("country", sa.Text),
            sa.column("language", sa.Text),
            sa.column("feed_url", sa.Text),
            sa.column("collection_mode", sa.String),
            sa.column("enabled", sa.Boolean),
        ),
        [
            dict(
                zip(
                    ("slug", "name", "source_kind", "country", "language", "feed_url", "collection_mode", "enabled"),
                    row,
                )
            )
            for row in DOCUMENT_SOURCE_SEED
        ],
        # offline(`--sql`)에서는 executemany를 찍을 수 없다. 행마다 INSERT를 내게 한다.
        multiinsert=False,
    )
    # ### end Alembic commands ###


def downgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_document_source_record_id", table_name="document")
    op.drop_index("ix_document_published_at", table_name="document")
    op.drop_index("ix_document_content_hash", table_name="document")
    op.drop_index("ix_document_canonical_document_id", table_name="document")
    op.drop_table("document")
    op.drop_table("document_source")
    # ### end Alembic commands ###


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
