"""clarify quote bar volume comment

Revision ID: 639bb9478796
Revises: 48eb0cf0a589
Create Date: 2026-08-08 21:46:19.525763

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "639bb9478796"
down_revision: str | Sequence[str] | None = "48eb0cf0a589"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quote_bar",
        "volume",
        existing_type=sa.BIGINT(),
        comment="봉 구간의 거래량. 제공처가 주는 값을 그대로 저장한다. 현물 지수처럼 거래량 개념이 없는 심볼은 제공처가 0을 실어 보내므로 0이 들어간다. 즉 0은 '거래가 없었다'와 '제공처가 거래량을 주지 않는다'를 구분하지 않는다. 거래량으로 판단하는 조회가 생기면 그때 심볼 종류로 갈라 읽는다",
        existing_comment="봉 구간의 거래량. 제공처가 주지 않으면 NULL이다(지수 선물은 0으로 오기도 한다)",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quote_bar",
        "volume",
        existing_type=sa.BIGINT(),
        comment="봉 구간의 거래량. 제공처가 주지 않으면 NULL이다(지수 선물은 0으로 오기도 한다)",
        existing_comment="봉 구간의 거래량. 제공처가 주는 값을 그대로 저장한다. 현물 지수처럼 거래량 개념이 없는 심볼은 제공처가 0을 실어 보내므로 0이 들어간다. 즉 0은 '거래가 없었다'와 '제공처가 거래량을 주지 않는다'를 구분하지 않는다. 거래량으로 판단하는 조회가 생기면 그때 심볼 종류로 갈라 읽는다",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
