"""create disclosure_event and earnings_fact tables

Revision ID: 70d4f10af89d
Revises: 4c38c3f6a86a
Create Date: 2026-08-13 00:18:34.014304

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70d4f10af89d"
down_revision: str | Sequence[str] | None = "4c38c3f6a86a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disclosure_event",
        sa.Column(
            "provider",
            sa.Text(),
            nullable=False,
            comment="데이터 제공처 식별자(dart). 같은 수집의 source_record.source와 같은 값이다",
        ),
        sa.Column(
            "corp_code", sa.Text(), nullable=False, comment="DART 회사 고유번호(예: 00126380). 종목코드와 다른 체계다"
        ),
        sa.Column("stock_code", sa.Text(), nullable=False, comment="한국거래소 종목코드(예: 005930)"),
        sa.Column("company_name", sa.Text(), nullable=False, comment="DART가 준 회사명 원문"),
        sa.Column(
            "rcept_no",
            sa.Text(),
            nullable=False,
            comment="DART 접수번호. 공시·원문·재무제표를 잇는 키이며 제공처 안에서 고유하다",
        ),
        sa.Column(
            "report_name",
            sa.Text(),
            nullable=False,
            comment="보고서명 원문. 정정 접두사를 포함해 손대지 않고 그대로 저장한다",
        ),
        sa.Column("filer_name", sa.Text(), nullable=False, comment="제출인 이름 원문(flr_nm)"),
        sa.Column(
            "corp_class",
            sa.Text(),
            nullable=False,
            comment="DART 법인 구분(corp_cls). Y=유가증권, K=코스닥, N=코넥스, E=기타",
        ),
        sa.Column(
            "receipt_date",
            sa.Date(),
            nullable=False,
            comment="DART 접수일(rcept_dt). 날짜뿐이고 시·분이 없다. 기준 시간대는 한국이다",
        ),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="이 접수번호를 처음 수집한 시각(UTC). 재수집해도 갱신하지 않는다. 실제 공시 시각이 아니라 최초 감지 시각이므로 화면에도 그렇게 표시한다. 2분 폴링이라 공시 시각의 상한이며 오차는 폴링 주기와 DART 반영 지연의 합이다",
        ),
        sa.Column(
            "remarks",
            sa.Text(),
            nullable=True,
            comment="DART 비고 원문(rm). 정정·철회·유가증권신고서 관련 표시가 들어온다",
        ),
        sa.Column(
            "source_record_id",
            sa.BigInteger(),
            nullable=False,
            comment="이 행을 만든 회사별 공시 목록 조회의 source_record 레코드 ID",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "rcept_no", name="uq_disclosure_event_natural_key"),
        comment="DART 공시 접수 이벤트를 접수번호 단위로 보존하는 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index("ix_disclosure_event_source_record_id", "disclosure_event", ["source_record_id"], unique=False)
    op.create_index(
        "ix_disclosure_event_stock_code_receipt_date", "disclosure_event", ["stock_code", "receipt_date"], unique=False
    )
    op.create_table(
        "earnings_fact",
        sa.Column(
            "provider",
            sa.Text(),
            nullable=False,
            comment="데이터 제공처 식별자(dart). 같은 수집의 source_record.source와 같은 값이다",
        ),
        sa.Column("stock_code", sa.Text(), nullable=False, comment="한국거래소 종목코드(예: 005930)"),
        sa.Column(
            "rcept_no",
            sa.Text(),
            nullable=False,
            comment="숫자의 출처가 된 공시의 DART 접수번호. disclosure_event와 같은 값이지만 외래키는 걸지 않는다",
        ),
        sa.Column(
            "release_type",
            sa.Enum("provisional", "periodic", name="earningsreleasetype", native_enum=False, length=20),
            nullable=False,
            comment="숫자의 출처 종류(provisional=잠정실적 공시 원문, periodic=정기보고서 재무제표 API)",
        ),
        sa.Column(
            "period_end",
            sa.Date(),
            nullable=False,
            comment="실적 대상 기간의 종료일(예: 2026-06-30). 기준 시간대는 한국이다",
        ),
        sa.Column(
            "statement_scope",
            sa.Enum("CFS", "OFS", name="statementscope", native_enum=False, length=20),
            nullable=False,
            comment="재무제표 범위(CFS=연결, OFS=별도). 연결을 우선하고 없을 때만 별도를 저장한다",
        ),
        sa.Column(
            "amount_basis",
            sa.Enum("period", "cumulative", name="amountbasis", native_enum=False, length=20),
            nullable=False,
            comment="금액의 기간 기준(period=해당 분기·반기, cumulative=사업연도 누계)",
        ),
        sa.Column(
            "metric",
            sa.Enum("revenue", "operating_profit", "net_income", name="earningsmetric", native_enum=False, length=20),
            nullable=False,
            comment="지표(revenue=매출액, operating_profit=영업이익, net_income=당기순이익)",
        ),
        sa.Column(
            "current_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="당기 금액. 원문 단위를 원 단위로 정규화한 값이며 음수와 0은 정상값이다",
        ),
        sa.Column(
            "prior_year_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=True,
            comment="비교 가능한 전년 동기 금액(원). 원문에 없으면 NULL이고 0으로 바꾸지 않는다",
        ),
        sa.Column("currency", sa.Text(), nullable=False, comment="원문이 밝힌 통화(예: KRW). 임의로 환산하지 않는다"),
        sa.Column(
            "source_account_id",
            sa.Text(),
            nullable=True,
            comment="OpenDART 원계정 ID(예: ifrs-full_Revenue). 원문 표에서 읽은 잠정실적은 NULL이다",
        ),
        sa.Column(
            "source_account_name",
            sa.Text(),
            nullable=False,
            comment="원문 항목명. 어느 줄에서 읽은 숫자인지 되짚을 근거다",
        ),
        sa.Column(
            "source_record_id",
            sa.BigInteger(),
            nullable=False,
            comment="숫자를 얻은 원문 또는 재무제표 API 조회의 source_record 레코드 ID",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.CheckConstraint("amount_basis IN ('period', 'cumulative')", name="ck_earnings_fact_amount_basis"),
        sa.CheckConstraint("metric IN ('revenue', 'operating_profit', 'net_income')", name="ck_earnings_fact_metric"),
        sa.CheckConstraint("release_type IN ('provisional', 'periodic')", name="ck_earnings_fact_release_type"),
        sa.CheckConstraint("statement_scope IN ('CFS', 'OFS')", name="ck_earnings_fact_statement_scope"),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "rcept_no", "statement_scope", "amount_basis", "metric", name="uq_earnings_fact_natural_key"
        ),
        comment="DART 공시에서 추출한 실적 지표를 지표당 한 행으로 저장하는 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index("ix_earnings_fact_source_record_id", "earnings_fact", ["source_record_id"], unique=False)
    op.create_index(
        "ix_earnings_fact_stock_code_period_end", "earnings_fact", ["stock_code", "period_end"], unique=False
    )
    op.alter_column(
        "market_session",
        "market_code",
        existing_type=sa.VARCHAR(length=20),
        comment="휴장 캘린더를 공유하는 시장 묶음(KRX, US_EQUITY). 상장 거래소를 뜻하는 Market enum과는 다른 체계다",
        existing_comment="휴장 캘린더를 공유하는 시장 묶음(KRX, US_EQUITY). reference.market과는 다른 체계다",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "market_session",
        "market_code",
        existing_type=sa.VARCHAR(length=20),
        comment="휴장 캘린더를 공유하는 시장 묶음(KRX, US_EQUITY). reference.market과는 다른 체계다",
        existing_comment="휴장 캘린더를 공유하는 시장 묶음(KRX, US_EQUITY). 상장 거래소를 뜻하는 Market enum과는 다른 체계다",
        existing_nullable=False,
    )
    op.drop_index("ix_earnings_fact_stock_code_period_end", table_name="earnings_fact")
    op.drop_index("ix_earnings_fact_source_record_id", table_name="earnings_fact")
    op.drop_table("earnings_fact")
    op.drop_index("ix_disclosure_event_stock_code_receipt_date", table_name="disclosure_event")
    op.drop_index("ix_disclosure_event_source_record_id", table_name="disclosure_event")
    op.drop_table("disclosure_event")
    # ### end Alembic commands ###


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
