"""create quote bar table

Revision ID: 9c1faba10bf1
Revises: a2e57b3c8f41
Create Date: 2026-08-08 10:53:37.099618

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c1faba10bf1"
down_revision: str | Sequence[str] | None = "a2e57b3c8f41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quote_bar",
        sa.Column(
            "provider",
            sa.Text(),
            nullable=False,
            comment="데이터 제공처 식별자(예: yahoo 또는 kis). 같은 수집의 source_record.source와 같은 값이다",
        ),
        sa.Column(
            "symbol",
            sa.Text(),
            nullable=False,
            comment="시세 대상 식별자(예: SP500_FUT, SOX). 제공처 안에서만 고유하다",
        ),
        sa.Column(
            "bar_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="1분봉이 시작하는 시각(UTC). 봉은 이 시각부터 1분간의 거래를 담는다",
        ),
        sa.Column("open", sa.Numeric(precision=18, scale=8), nullable=False, comment="봉 구간의 시가"),
        sa.Column("high", sa.Numeric(precision=18, scale=8), nullable=False, comment="봉 구간의 고가"),
        sa.Column("low", sa.Numeric(precision=18, scale=8), nullable=False, comment="봉 구간의 저가"),
        sa.Column("close", sa.Numeric(precision=18, scale=8), nullable=False, comment="봉 구간의 종가"),
        sa.Column(
            "volume",
            sa.BigInteger(),
            nullable=True,
            comment="봉 구간의 거래량. 제공처가 주지 않으면 NULL이다(지수 선물은 0으로 오기도 한다)",
        ),
        sa.Column(
            "previous_close",
            sa.Numeric(precision=18, scale=8),
            nullable=False,
            comment="직전 정규장 종가. 알림이 쓰는 변동률의 분모다. 봉마다 같은 값이 반복되지만 세션 경계 계산을 피하려고 그대로 저장한다",
        ),
        sa.Column("source_record_id", sa.BigInteger(), nullable=False, comment="근거가 되는 source_record 레코드 ID"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "symbol", "bar_at", name="uq_quote_bar_natural_key"),
        comment="지수·선물의 1분봉을 장중 알림 판단용으로 누적하는 테이블",
    )
    op.create_index("ix_quote_bar_source_record_id", "quote_bar", ["source_record_id"], unique=False)
    # ### end Alembic commands ###


def downgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_quote_bar_source_record_id", table_name="quote_bar")
    op.drop_table("quote_bar")
    # ### end Alembic commands ###


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
