"""create krx market positioning tables

Revision ID: b186ab47dbd8
Revises: 4bb73b5f30e0
Create Date: 2026-08-13 13:04:29.256913

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b186ab47dbd8"
down_revision: str | Sequence[str] | None = "4bb73b5f30e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "krx_credit_balance_ranking_daily",
        sa.Column("provider", sa.Text(), nullable=False, comment="데이터 제공처 식별자(kis)"),
        sa.Column(
            "standard_date", sa.Date(), nullable=False, comment="순위 기준일(응답 stnd_date2). 둘 중 최신 날짜다"
        ),
        sa.Column(
            "comparison_date",
            sa.Date(),
            nullable=False,
            comment="증가율 비교일(응답 stnd_date1). 기준일보다 period_days 영업일 앞이다",
        ),
        sa.Column("universe_code", sa.Text(), nullable=False, comment="조회 대상 코드(FID_INPUT_ISCD). 0000은 전체다"),
        sa.Column(
            "sort_code", sa.Text(), nullable=False, comment="정렬 코드(FID_RANK_SORT_CLS_CODE). 2는 융자잔고금액 상위다"
        ),
        sa.Column("period_days", sa.Integer(), nullable=False, comment="증가율 비교 기간(FID_OPTION). 영업일 수다"),
        sa.Column(
            "rank",
            sa.Integer(),
            nullable=False,
            comment="순위. 응답에 순번 필드가 없어 배열 순서로 1부터 매긴다(실측: 순번 필드 없음)",
        ),
        sa.Column("stock_code", sa.Text(), nullable=False, comment="한국거래소 종목코드 6자리(mksc_shrn_iscd)"),
        sa.Column("stock_name", sa.Text(), nullable=False, comment="종목명 원문(hts_kor_isnm)"),
        sa.Column("close_price", sa.Numeric(precision=18, scale=4), nullable=False, comment="현재가(stck_prpr). 원"),
        sa.Column("accumulated_volume", sa.BigInteger(), nullable=False, comment="누적 거래량(acml_vol). 주"),
        sa.Column(
            "loan_balance_quantity", sa.BigInteger(), nullable=False, comment="융자 잔고 수량(whol_loan_rmnd_stcn). 주"
        ),
        sa.Column(
            "loan_balance_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="융자 잔고 금액(whol_loan_rmnd_amt). 정렬 기준 값이다",
        ),
        sa.Column(
            "loan_balance_rate",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="융자 잔고 비율(whol_loan_rmnd_rate). KIS 표기 그대로의 퍼센트",
        ),
        sa.Column(
            "short_loan_balance_quantity",
            sa.BigInteger(),
            nullable=False,
            comment="신용대주 잔고 수량(whol_stln_rmnd_stcn). 주",
        ),
        sa.Column(
            "short_loan_balance_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="신용대주 잔고 금액(whol_stln_rmnd_amt)",
        ),
        sa.Column(
            "short_loan_balance_rate",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="신용대주 잔고 비율(whol_stln_rmnd_rate). KIS 표기 그대로의 퍼센트",
        ),
        sa.Column(
            "loan_balance_growth_rate",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="비교일 대비 융자잔고 증가율(nday_vrss_loan_rmnd_inrt). 변화량이 아니라 증가율이다",
        ),
        sa.Column(
            "short_loan_balance_growth_rate",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="비교일 대비 신용대주잔고 증가율(nday_vrss_stln_rmnd_inrt). 변화량이 아니라 증가율이다",
        ),
        sa.Column(
            "source_record_id",
            sa.BigInteger(),
            nullable=False,
            comment="이 행을 마지막으로 갱신한 수집의 source_record 레코드 ID",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.CheckConstraint("rank >= 1", name="ck_krx_credit_balance_ranking_daily_rank"),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider",
            "standard_date",
            "universe_code",
            "sort_code",
            "period_days",
            "rank",
            name="uq_krx_credit_balance_ranking_daily_natural_key",
        ),
        comment="융자잔고금액 상위 종목의 일별 순위 스냅샷을 저장하는 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index(
        "ix_krx_credit_balance_ranking_daily_source_record_id",
        "krx_credit_balance_ranking_daily",
        ["source_record_id"],
        unique=False,
    )
    op.create_index(
        "ix_krx_credit_balance_ranking_daily_stock_code",
        "krx_credit_balance_ranking_daily",
        ["stock_code", "standard_date"],
        unique=False,
    )
    op.create_table(
        "krx_market_funds_daily",
        sa.Column("provider", sa.Text(), nullable=False, comment="데이터 제공처 식별자(kis)"),
        sa.Column(
            "business_date",
            sa.Date(),
            nullable=False,
            comment="응답이 준 영업일(bsop_date). 요청일이나 수집일을 대신 넣지 않는다",
        ),
        sa.Column(
            "index_close", sa.Numeric(precision=18, scale=4), nullable=False, comment="그날 시장지수(bstp_nmix_prpr)"
        ),
        sa.Column(
            "index_change",
            sa.Numeric(precision=18, scale=4),
            nullable=False,
            comment="지수 전일대비(bstp_nmix_prdy_vrss)",
        ),
        sa.Column(
            "market_capitalization",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="시가총액(hts_avls). 포털 표기는 백만원이며 환산하지 않는다",
        ),
        sa.Column(
            "customer_deposit",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="고객예탁금(cust_dpmn_amt). 포털 표기는 억원이며 환산하지 않는다",
        ),
        sa.Column(
            "customer_deposit_change",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="고객예탁금 전일대비(cust_dpmn_amt_prdy_vrss). 음수는 정상값이다",
        ),
        sa.Column(
            "turnover_ratio",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="금액 회전율(amt_tnrt). KIS 표기 그대로의 퍼센트",
        ),
        sa.Column(
            "unsettled_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="미수금(uncl_amt). 포털 표기는 억원이며 환산하지 않는다",
        ),
        sa.Column(
            "credit_loan_balance",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="신용융자 잔고(crdt_loan_rmnd). 포털 표기는 억원이며 환산하지 않는다",
        ),
        sa.Column(
            "futures_margin_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="선물 관련 자금(futs_tfam_amt)",
        ),
        sa.Column(
            "equity_fund_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="주식형 펀드 설정액(sttp_amt)",
        ),
        sa.Column(
            "mixed_fund_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="혼합형 펀드 설정액(mxtp_amt)",
        ),
        sa.Column(
            "bond_fund_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="채권형 펀드 설정액(bntp_amt)",
        ),
        sa.Column("mmf_amount", sa.Numeric(precision=24, scale=2), nullable=False, comment="MMF 설정액(mmf_amt)"),
        sa.Column(
            "securities_lending_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="대차 금액(secu_lend_amt)",
        ),
        sa.Column(
            "source_record_id",
            sa.BigInteger(),
            nullable=False,
            comment="이 행을 마지막으로 갱신한 수집의 source_record 레코드 ID",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "business_date", name="uq_krx_market_funds_daily_natural_key"),
        comment="고객예탁금·신용융자·펀드 등 국내 증시자금 종합을 영업일 단위로 누적하는 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index(
        "ix_krx_market_funds_daily_source_record_id", "krx_market_funds_daily", ["source_record_id"], unique=False
    )
    op.create_table(
        "krx_stock_credit_balance_daily",
        sa.Column(
            "provider",
            sa.Text(),
            nullable=False,
            comment="데이터 제공처 식별자(kis). 같은 수집의 source_record.source와 같은 값이다",
        ),
        sa.Column(
            "stock_code",
            sa.Text(),
            nullable=False,
            comment="한국거래소 종목코드 6자리(예: 005930). disclosure_event.stock_code와 같은 체계다",
        ),
        sa.Column(
            "trade_date", sa.Date(), nullable=False, comment="값이 만들어진 거래일(deal_date). 기준 시간대는 한국이다"
        ),
        sa.Column(
            "settlement_date",
            sa.Date(),
            nullable=False,
            comment="결제일(stlm_date). 거래일보다 통상 2영업일 뒤다(실측)",
        ),
        sa.Column(
            "close_price", sa.Numeric(precision=18, scale=4), nullable=False, comment="그 거래일 종가(stck_prpr). 원"
        ),
        sa.Column("accumulated_volume", sa.BigInteger(), nullable=False, comment="그 거래일 누적 거래량(acml_vol). 주"),
        sa.Column(
            "loan_new_quantity", sa.BigInteger(), nullable=False, comment="융자 신규 수량(whol_loan_new_stcn). 주"
        ),
        sa.Column(
            "loan_repayment_quantity",
            sa.BigInteger(),
            nullable=False,
            comment="융자 상환 수량(whol_loan_rdmp_stcn). 주",
        ),
        sa.Column(
            "loan_balance_quantity", sa.BigInteger(), nullable=False, comment="융자 잔고 수량(whol_loan_rmnd_stcn). 주"
        ),
        sa.Column(
            "loan_new_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="융자 신규 금액(whol_loan_new_amt). KIS 표기 그대로 저장한다",
        ),
        sa.Column(
            "loan_repayment_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="융자 상환 금액(whol_loan_rdmp_amt). KIS 표기 그대로 저장한다",
        ),
        sa.Column(
            "loan_balance_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="융자 잔고 금액(whol_loan_rmnd_amt). KIS 표기 그대로 저장한다",
        ),
        sa.Column(
            "loan_balance_rate",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="융자 잔고 비율(whol_loan_rmnd_rate). KIS 표기 그대로의 퍼센트",
        ),
        sa.Column(
            "loan_supply_rate",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="융자 공여율(whol_loan_gvrt). KIS 표기 그대로의 퍼센트",
        ),
        sa.Column(
            "short_loan_new_quantity",
            sa.BigInteger(),
            nullable=False,
            comment="신용대주 신규 수량(whol_stln_new_stcn). 주",
        ),
        sa.Column(
            "short_loan_repayment_quantity",
            sa.BigInteger(),
            nullable=False,
            comment="신용대주 상환 수량(whol_stln_rdmp_stcn). 주",
        ),
        sa.Column(
            "short_loan_balance_quantity",
            sa.BigInteger(),
            nullable=False,
            comment="신용대주 잔고 수량(whol_stln_rmnd_stcn). 주",
        ),
        sa.Column(
            "short_loan_new_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="신용대주 신규 금액(whol_stln_new_amt). KIS 표기 그대로 저장한다",
        ),
        sa.Column(
            "short_loan_repayment_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="신용대주 상환 금액(whol_stln_rdmp_amt). KIS 표기 그대로 저장한다",
        ),
        sa.Column(
            "short_loan_balance_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="신용대주 잔고 금액(whol_stln_rmnd_amt). KIS 표기 그대로 저장한다",
        ),
        sa.Column(
            "short_loan_balance_rate",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="신용대주 잔고 비율(whol_stln_rmnd_rate). KIS 표기 그대로의 퍼센트",
        ),
        sa.Column(
            "short_loan_supply_rate",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="신용대주 공여율(whol_stln_gvrt). KIS 표기 그대로의 퍼센트",
        ),
        sa.Column(
            "source_record_id",
            sa.BigInteger(),
            nullable=False,
            comment="이 행을 마지막으로 갱신한 수집의 source_record 레코드 ID",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "stock_code", "trade_date", name="uq_krx_stock_credit_balance_daily_natural_key"
        ),
        comment="종목별 신용잔고(융자·신용대주) 일별추이를 거래일 기준으로 누적하는 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index(
        "ix_krx_stock_credit_balance_daily_source_record_id",
        "krx_stock_credit_balance_daily",
        ["source_record_id"],
        unique=False,
    )
    op.create_table(
        "krx_stock_securities_lending_daily",
        sa.Column("provider", sa.Text(), nullable=False, comment="데이터 제공처 식별자(kis)"),
        sa.Column("stock_code", sa.Text(), nullable=False, comment="한국거래소 종목코드 6자리(예: 005930)"),
        sa.Column("business_date", sa.Date(), nullable=False, comment="영업일(bsop_date). 기준 시간대는 한국이다"),
        sa.Column("close_price", sa.Numeric(precision=18, scale=4), nullable=False, comment="그날 종가(stck_prpr). 원"),
        sa.Column(
            "price_change",
            sa.Numeric(precision=18, scale=4),
            nullable=False,
            comment="전일대비 가격(prdy_vrss). 음수는 정상값이다",
        ),
        sa.Column("accumulated_volume", sa.BigInteger(), nullable=False, comment="그날 누적 거래량(acml_vol). 주"),
        sa.Column("new_quantity", sa.BigInteger(), nullable=False, comment="대차 신규 체결 수량(new_stcn). 주"),
        sa.Column("repayment_quantity", sa.BigInteger(), nullable=False, comment="대차 상환 수량(rdmp_stcn). 주"),
        sa.Column(
            "balance_change_quantity",
            sa.BigInteger(),
            nullable=False,
            comment="전일대비 잔고 증감 수량(prdy_rmnd_vrss). 음수는 정상값이다",
        ),
        sa.Column("balance_quantity", sa.BigInteger(), nullable=False, comment="대차 잔고 수량(rmnd_stcn). 주"),
        sa.Column(
            "balance_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="대차 잔고 금액(rmnd_amt). **백만원 단위다**(실측: 잔고수량×종가의 1/1,000,000)",
        ),
        sa.Column(
            "source_record_id",
            sa.BigInteger(),
            nullable=False,
            comment="이 행을 마지막으로 갱신한 수집의 source_record 레코드 ID",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "stock_code", "business_date", name="uq_krx_stock_securities_lending_daily_natural_key"
        ),
        comment="종목별 대차거래 신규·상환·잔고를 영업일 단위로 누적하는 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index(
        "ix_krx_stock_securities_lending_daily_source_record_id",
        "krx_stock_securities_lending_daily",
        ["source_record_id"],
        unique=False,
    )
    op.create_table(
        "krx_stock_short_sale_daily",
        sa.Column("provider", sa.Text(), nullable=False, comment="데이터 제공처 식별자(kis)"),
        sa.Column("stock_code", sa.Text(), nullable=False, comment="한국거래소 종목코드 6자리(예: 005930)"),
        sa.Column("business_date", sa.Date(), nullable=False, comment="영업일(stck_bsop_date). 기준 시간대는 한국이다"),
        sa.Column("close_price", sa.Numeric(precision=18, scale=4), nullable=False, comment="그날 종가(stck_clpr). 원"),
        sa.Column("accumulated_volume", sa.BigInteger(), nullable=False, comment="그날 누적 거래량(acml_vol). 주"),
        sa.Column(
            "short_sale_quantity", sa.BigInteger(), nullable=False, comment="그날 공매도 체결수량(ssts_cntg_qty). 주"
        ),
        sa.Column(
            "short_sale_volume_ratio",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="공매도 거래량 비중(ssts_vol_rlim). KIS 표기 그대로의 퍼센트",
        ),
        sa.Column(
            "accumulated_short_sale_quantity",
            sa.BigInteger(),
            nullable=False,
            comment="누적 공매도 수량(acml_ssts_cntg_qty). 주",
        ),
        sa.Column(
            "accumulated_short_sale_volume_ratio",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="누적 공매도 거래량 비중(acml_ssts_cntg_qty_rlim). 퍼센트",
        ),
        sa.Column(
            "short_sale_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="그날 공매도 거래대금(ssts_tr_pbmn). **원 단위다**(실측: 수량×종가와 거의 같다)",
        ),
        sa.Column(
            "short_sale_amount_ratio",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="공매도 거래대금 비중(ssts_tr_pbmn_rlim). 퍼센트",
        ),
        sa.Column(
            "accumulated_short_sale_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="누적 공매도 거래대금(acml_ssts_tr_pbmn). 원",
        ),
        sa.Column(
            "accumulated_short_sale_amount_ratio",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="누적 공매도 거래대금 비중(acml_ssts_tr_pbmn_rlim). 퍼센트",
        ),
        sa.Column(
            "total_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="그날 전체 거래대금(acml_tr_pbmn). 원",
        ),
        sa.Column(
            "short_sale_average_price",
            sa.Numeric(precision=18, scale=4),
            nullable=False,
            comment="공매도 평균가(avrg_prc). 원",
        ),
        sa.Column(
            "source_record_id",
            sa.BigInteger(),
            nullable=False,
            comment="이 행을 마지막으로 갱신한 수집의 source_record 레코드 ID",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "stock_code", "business_date", name="uq_krx_stock_short_sale_daily_natural_key"
        ),
        comment="종목별 공매도 체결수량·거래대금과 그 비중을 영업일 단위로 누적하는 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index(
        "ix_krx_stock_short_sale_daily_source_record_id",
        "krx_stock_short_sale_daily",
        ["source_record_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_krx_stock_short_sale_daily_source_record_id", table_name="krx_stock_short_sale_daily")
    op.drop_table("krx_stock_short_sale_daily")
    op.drop_index(
        "ix_krx_stock_securities_lending_daily_source_record_id", table_name="krx_stock_securities_lending_daily"
    )
    op.drop_table("krx_stock_securities_lending_daily")
    op.drop_index("ix_krx_stock_credit_balance_daily_source_record_id", table_name="krx_stock_credit_balance_daily")
    op.drop_table("krx_stock_credit_balance_daily")
    op.drop_index("ix_krx_market_funds_daily_source_record_id", table_name="krx_market_funds_daily")
    op.drop_table("krx_market_funds_daily")
    op.drop_index("ix_krx_credit_balance_ranking_daily_stock_code", table_name="krx_credit_balance_ranking_daily")
    op.drop_index("ix_krx_credit_balance_ranking_daily_source_record_id", table_name="krx_credit_balance_ranking_daily")
    op.drop_table("krx_credit_balance_ranking_daily")
    # ### end Alembic commands ###


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
