"""create krx market securities lending table

Revision ID: b31d45ced431
Revises: a7166edaab6b
Create Date: 2026-08-14 09:27:04.577027

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b31d45ced431"
down_revision: str | Sequence[str] | None = "a7166edaab6b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "krx_market_securities_lending_daily",
        sa.Column("provider", sa.Text(), nullable=False, comment="데이터 제공처 식별자(kis)"),
        sa.Column(
            "market_code",
            sa.Enum("KOSPI", "KOSDAQ", name="krxmarket", native_enum=False, length=20),
            nullable=False,
            comment="시장 구분(KOSPI, KOSDAQ). market_movement_snapshot.symbol과 같은 값 집합이다",
        ),
        sa.Column("business_date", sa.Date(), nullable=False, comment="영업일(bsop_date). 기준 시간대는 한국이다"),
        sa.Column(
            "index_close",
            sa.Numeric(precision=18, scale=4),
            nullable=False,
            comment="그날 시장지수 종가(stck_prpr). 종목 조회에서는 주가지만 시장 조회에서는 지수다",
        ),
        sa.Column(
            "index_change",
            sa.Numeric(precision=18, scale=4),
            nullable=False,
            comment="지수 전일대비(prdy_vrss). 음수는 정상값이다",
        ),
        sa.Column("accumulated_volume", sa.BigInteger(), nullable=False, comment="그날 시장 전체 거래량(acml_vol). 주"),
        sa.Column("new_quantity", sa.BigInteger(), nullable=False, comment="대차 신규 체결 수량(new_stcn). 주"),
        sa.Column("repayment_quantity", sa.BigInteger(), nullable=False, comment="대차 상환 수량(rdmp_stcn). 주"),
        sa.Column(
            "balance_change_quantity",
            sa.BigInteger(),
            nullable=False,
            comment="전일대비 잔고 증감 수량(prdy_rmnd_vrss). 음수는 정상값이다",
        ),
        sa.Column(
            "balance_quantity", sa.BigInteger(), nullable=False, comment="시장 전체 대차 잔고 수량(rmnd_stcn). 주"
        ),
        sa.Column(
            "balance_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="시장 전체 대차 잔고 금액(rmnd_amt). **백만원 단위다**(종목 대차와 같은 표기)",
        ),
        sa.Column(
            "source_record_id",
            sa.BigInteger(),
            nullable=False,
            comment="이 행을 마지막으로 갱신한 수집의 source_record 레코드 ID",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.CheckConstraint(
            "market_code IN ('KOSPI', 'KOSDAQ')", name="ck_krx_market_securities_lending_daily_market_code"
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "market_code", "business_date", name="uq_krx_market_securities_lending_daily_natural_key"
        ),
        comment="코스피·코스닥 시장 전체의 대차거래 신규·상환·잔고를 영업일 단위로 누적하는 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index(
        "ix_krx_market_securities_lending_daily_source_record_id",
        "krx_market_securities_lending_daily",
        ["source_record_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_krx_market_securities_lending_daily_source_record_id", table_name="krx_market_securities_lending_daily"
    )
    op.drop_table("krx_market_securities_lending_daily")
    # ### end Alembic commands ###


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
