"""move exchange_rate to default

Revision ID: b3d0a15c7e42
Revises: 9c4be2f1a70d
Create Date: 2026-08-06 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3d0a15c7e42"
down_revision: str | Sequence[str] | None = "9c4be2f1a70d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLE = "exchange_rate"


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # `exchange_rate` moves from the `finance` alias to this one. The DDL is a
    # byte-for-byte copy of the finance table so the two stay comparable: the
    # collector writes here, and the finance rows can still be loaded later
    # without a column-by-column translation.
    #
    # That is also why this table breaks the project's own conventions - SERIAL
    # instead of BIGSERIAL, naive timestamps, no comments. See the module
    # docstring of `apps/models/finance.py`.
    op.create_table(
        TABLE,
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.Column("buy", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("sell", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("send", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("receive", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("exchange_standard_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("currency", "date", "time", "round", name="unique_currency_date_time_round"),
    )
    op.create_index("idx_exchange_rate_date", TABLE, ["date"], unique=False)
    op.create_index("idx_exchange_rate_currency_date", TABLE, ["currency", "date"], unique=False)


def downgrade_default() -> None:
    # This alias owns its copy, so dropping it here is safe. The finance table
    # is a different database and is not touched.
    op.drop_index("idx_exchange_rate_currency_date", table_name=TABLE)
    op.drop_index("idx_exchange_rate_date", table_name=TABLE)
    op.drop_table(TABLE)


def upgrade_finance() -> None:
    # Written by hand, not autogenerated. Autogenerate sees the model leave this
    # alias and proposes `DROP TABLE exchange_rate` here - which would destroy a
    # live table this project does not own. The finance table stays exactly as it
    # is; only `alembic_version_finance` moves forward.
    #
    # From this revision on, no model maps to the `finance` alias, so future
    # autogenerate runs have nothing to compare and emit nothing for it.
    pass


def downgrade_finance() -> None:
    pass
