"""create investor flow tables

Revision ID: c8a69f7e741a
Revises: b31d45ced431
Create Date: 2026-08-14 14:52:02.517349

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8a69f7e741a"
down_revision: str | Sequence[str] | None = "b31d45ced431"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_investor_flow_snapshot",
        sa.Column("provider", sa.Text(), nullable=False, comment="데이터 제공처 식별자(kis)"),
        sa.Column(
            "market_code",
            sa.Enum("KOSPI", "KOSDAQ", name="krxmarket", native_enum=False, length=20),
            nullable=False,
            comment="시장 구분(KOSPI, KOSDAQ). 코스닥 조회 코드는 아직 확인하지 못해 KOSPI만 채워진다",
        ),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="관측이 속한 1분의 시작 시각(UTC). 응답에 원천 시각이 없어 수집 시각을 절삭한 값이다",
        ),
        sa.Column(
            "foreign_sell_qty",
            sa.BigInteger(),
            nullable=False,
            comment="외국인 누적 매도 수량(frgn_seln_vol). 단위 미확정이라 환산하지 않는다",
        ),
        sa.Column("foreign_buy_qty", sa.BigInteger(), nullable=False, comment="외국인 누적 매수 수량(frgn_shnu_vol)"),
        sa.Column(
            "foreign_net_buy_qty",
            sa.BigInteger(),
            nullable=False,
            comment="외국인 순매수 수량(frgn_ntby_qty). 매수-매도와 일치하는지 검증한다",
        ),
        sa.Column(
            "foreign_net_buy_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="외국인 순매수 대금(frgn_ntby_tr_pbmn). 단위 미확정",
        ),
        sa.Column(
            "institution_sell_qty", sa.BigInteger(), nullable=False, comment="기관 누적 매도 수량(orgn_seln_vol)"
        ),
        sa.Column("institution_buy_qty", sa.BigInteger(), nullable=False, comment="기관 누적 매수 수량(orgn_shnu_vol)"),
        sa.Column(
            "institution_net_buy_qty", sa.BigInteger(), nullable=False, comment="기관 순매수 수량(orgn_ntby_qty)"
        ),
        sa.Column(
            "institution_net_buy_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="기관 순매수 대금(orgn_ntby_tr_pbmn). 단위 미확정",
        ),
        sa.Column("individual_sell_qty", sa.BigInteger(), nullable=False, comment="개인 누적 매도 수량(prsn_seln_vol)"),
        sa.Column("individual_buy_qty", sa.BigInteger(), nullable=False, comment="개인 누적 매수 수량(prsn_shnu_vol)"),
        sa.Column("individual_net_buy_qty", sa.BigInteger(), nullable=False, comment="개인 순매수 수량(prsn_ntby_qty)"),
        sa.Column(
            "individual_net_buy_amount",
            sa.Numeric(precision=24, scale=2),
            nullable=False,
            comment="개인 순매수 대금(prsn_ntby_tr_pbmn). 단위 미확정",
        ),
        sa.Column(
            "securities_net_buy_qty",
            sa.BigInteger(),
            nullable=False,
            comment="금융투자 순매수 수량(scrt_ntby_qty). 기관계의 부분집합이다",
        ),
        sa.Column(
            "investment_trust_net_buy_qty",
            sa.BigInteger(),
            nullable=False,
            comment="투자신탁 순매수 수량(ivtr_ntby_qty). 기관계의 부분집합이다",
        ),
        sa.Column(
            "private_equity_net_buy_qty",
            sa.BigInteger(),
            nullable=False,
            comment="사모펀드 순매수 수량(pe_fund_ntby_vol). 이 분류만 접미사가 _vol이다",
        ),
        sa.Column(
            "bank_net_buy_qty",
            sa.BigInteger(),
            nullable=False,
            comment="은행 순매수 수량(bank_ntby_qty). 기관계의 부분집합이다",
        ),
        sa.Column(
            "insurance_net_buy_qty",
            sa.BigInteger(),
            nullable=False,
            comment="보험 순매수 수량(insu_ntby_qty). 기관계의 부분집합이다",
        ),
        sa.Column(
            "merchant_bank_net_buy_qty",
            sa.BigInteger(),
            nullable=False,
            comment="종금 순매수 수량(mrbn_ntby_qty). 기관계의 부분집합이다",
        ),
        sa.Column(
            "pension_fund_net_buy_qty",
            sa.BigInteger(),
            nullable=False,
            comment="기금 순매수 수량(fund_ntby_qty). 기관계의 부분집합이다",
        ),
        sa.Column(
            "other_corporation_net_buy_qty",
            sa.BigInteger(),
            nullable=False,
            comment="기타법인 순매수 수량(etc_corp_ntby_vol). 기관계 밖이며 접미사가 _vol이다",
        ),
        sa.Column(
            "other_organization_net_buy_qty",
            sa.BigInteger(),
            nullable=False,
            comment="기타단체 순매수 수량(etc_orgt_ntby_vol). 기관계 밖이며 접미사가 _vol이다",
        ),
        sa.Column(
            "source_record_id",
            sa.BigInteger(),
            nullable=False,
            comment="이 행을 마지막으로 갱신한 수집의 source_record 레코드 ID",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.CheckConstraint("market_code IN ('KOSPI', 'KOSDAQ')", name="ck_market_investor_flow_snapshot_market_code"),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "market_code", "observed_at", name="uq_market_investor_flow_snapshot_natural_key"
        ),
        comment="시장별 외국인·기관·개인의 장중 누적 매매동향을 분 단위로 누적하는 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index(
        "ix_market_investor_flow_snapshot_source_record_id",
        "market_investor_flow_snapshot",
        ["source_record_id"],
        unique=False,
    )
    op.create_table(
        "stock_investor_estimate_snapshot",
        sa.Column("provider", sa.Text(), nullable=False, comment="데이터 제공처 식별자(kis)"),
        sa.Column(
            "stock_code",
            sa.Text(),
            nullable=False,
            comment="한국거래소 종목코드 6자리(예: 005930). disclosure_event.stock_code와 같은 체계다",
        ),
        sa.Column(
            "business_date",
            sa.Date(),
            nullable=False,
            comment="이 값이 속한 거래일(KST). 응답에 날짜가 없어 수집 시각의 KST 날짜를 쓴다",
        ),
        sa.Column(
            "source_time_code",
            sa.Text(),
            nullable=False,
            comment="응답의 갱신 슬롯 코드(bsop_hour_gb). 시각이 아니라 코드이며 환산하지 않는다",
        ),
        sa.Column(
            "foreign_net_buy_qty",
            sa.BigInteger(),
            nullable=False,
            comment="외국인 추정 순매수 수량(frgn_fake_ntby_qty). 음수는 정상값이다",
        ),
        sa.Column(
            "institution_net_buy_qty",
            sa.BigInteger(),
            nullable=False,
            comment="기관 추정 순매수 수량(orgn_fake_ntby_qty). 음수는 정상값이다",
        ),
        sa.Column(
            "total_net_buy_qty",
            sa.BigInteger(),
            nullable=False,
            comment="합계 추정 순매수 수량(sum_fake_ntby_qty). 외국인+기관과 다르면 수집기가 실패시킨다",
        ),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="이 슬롯 값을 받은 시각(UTC). 자연키가 아니라 값이며 재수집하면 갱신된다",
        ),
        sa.Column(
            "source_record_id",
            sa.BigInteger(),
            nullable=False,
            comment="이 행을 마지막으로 갱신한 수집의 source_record 레코드 ID",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="레코드 고유 식별자"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider",
            "stock_code",
            "business_date",
            "source_time_code",
            name="uq_stock_investor_estimate_snapshot_natural_key",
        ),
        comment="종목별 외국인·기관 추정 순매수를 갱신 슬롯 단위로 누적하는 테이블",
        info={"database": "default", "managed": True},
    )
    op.create_index(
        "ix_stock_investor_estimate_snapshot_source_record_id",
        "stock_investor_estimate_snapshot",
        ["source_record_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_investor_estimate_snapshot_source_record_id", table_name="stock_investor_estimate_snapshot")
    op.drop_table("stock_investor_estimate_snapshot")
    op.drop_index("ix_market_investor_flow_snapshot_source_record_id", table_name="market_investor_flow_snapshot")
    op.drop_table("market_investor_flow_snapshot")
    # ### end Alembic commands ###


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
