"""comment exchange rate columns

Revision ID: e9640ef65120
Revises: b3d0a15c7e42
Create Date: 2026-08-06 15:29:30.937380

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e9640ef65120"
down_revision: str | Sequence[str] | None = "b3d0a15c7e42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # autogenerate가 붙인 `autoincrement=True`는 뺐다. MySQL 전용 인자라 PostgreSQL에서는
    # 경고만 내고 아무 일도 하지 않는다.
    op.alter_column(
        "exchange_rate", "id", existing_type=sa.INTEGER(), comment="레코드 고유 식별자", existing_nullable=False
    )
    op.alter_column(
        "exchange_rate",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="레코드 생성 시각. 원본 DDL을 따라 시간대가 없으며 DB 서버 시각으로 채워진다",
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "exchange_rate",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="레코드 최종 수정 시각. 갱신은 upsert가 직접 넣으며 DB 트리거는 없다",
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "exchange_rate",
        "currency",
        existing_type=sa.VARCHAR(length=10),
        comment="고시 통화 코드(ISO 4217). 허용 값은 Currency Enum이 정한다",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "round",
        existing_type=sa.INTEGER(),
        comment="같은 고시일자 안의 고시 회차. 1부터 증가하며 값이 클수록 나중 고시다",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "date",
        existing_type=sa.DATE(),
        comment="고시일자. 하나은행 기준이라 KST이며 컬럼에 시간대 정보는 없다",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "time",
        existing_type=postgresql.TIME(),
        comment="고시 시각. 고시일자와 같은 KST 기준이고 시간대 정보는 없다",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "buy",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment="현찰 사실 때 환율(원). 고객이 외화를 현찰로 살 때 적용된다",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "sell",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment="현찰 파실 때 환율(원). 고객이 외화를 현찰로 팔 때 적용된다",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "send",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment="송금 보낼 때 환율(원)",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "receive",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment="송금 받을 때 환율(원)",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "exchange_standard_rate",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment="매매기준율(원). 일부 통화는 0으로 고시되므로 조회 쪽에서 대체값을 쓴다",
        existing_nullable=False,
    )
    op.create_table_comment("exchange_rate", "하나은행이 고시한 통화별·회차별 환율", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("exchange_rate", existing_comment="하나은행이 고시한 통화별·회차별 환율", schema=None)
    op.alter_column(
        "exchange_rate",
        "exchange_standard_rate",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment=None,
        existing_comment="매매기준율(원). 일부 통화는 0으로 고시되므로 조회 쪽에서 대체값을 쓴다",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "receive",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment=None,
        existing_comment="송금 받을 때 환율(원)",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "send",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment=None,
        existing_comment="송금 보낼 때 환율(원)",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "sell",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment=None,
        existing_comment="현찰 파실 때 환율(원). 고객이 외화를 현찰로 팔 때 적용된다",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "buy",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment=None,
        existing_comment="현찰 사실 때 환율(원). 고객이 외화를 현찰로 살 때 적용된다",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "time",
        existing_type=postgresql.TIME(),
        comment=None,
        existing_comment="고시 시각. 고시일자와 같은 KST 기준이고 시간대 정보는 없다",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "date",
        existing_type=sa.DATE(),
        comment=None,
        existing_comment="고시일자. 하나은행 기준이라 KST이며 컬럼에 시간대 정보는 없다",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "round",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="같은 고시일자 안의 고시 회차. 1부터 증가하며 값이 클수록 나중 고시다",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "currency",
        existing_type=sa.VARCHAR(length=10),
        comment=None,
        existing_comment="고시 통화 코드(ISO 4217). 허용 값은 Currency Enum이 정한다",
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_rate",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="레코드 최종 수정 시각. 갱신은 upsert가 직접 넣으며 DB 트리거는 없다",
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "exchange_rate",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="레코드 생성 시각. 원본 DDL을 따라 시간대가 없으며 DB 서버 시각으로 채워진다",
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "exchange_rate",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="레코드 고유 식별자",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
