"""add tier3 symbols with crypto kind

Revision ID: f7c089e70905
Revises: 639bb9478796
Create Date: 2026-08-09 11:20:58.200055

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7c089e70905"
down_revision: str | Sequence[str] | None = "639bb9478796"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


KIND_COMMENT_BEFORE = (
    "값의 종류(index, index_future, fx, rate, bond_future, commodity, equity). "
    "화면을 가르는 기준이다. 거래 시간대가 다르고 정상 변동폭의 자릿수도 달라 "
    "한 축에 겹치면 읽을 수 없다"
)
KIND_COMMENT_AFTER = (
    "값의 종류(index, index_future, fx, rate, bond_future, commodity, equity, crypto). "
    "화면을 가르는 기준이다. 거래 시간대가 다르고 정상 변동폭의 자릿수도 달라 "
    "한 축에 겹치면 읽을 수 없다"
)

KINDS_BEFORE = "kind IN ('index', 'index_future', 'fx', 'rate', 'bond_future', 'commodity', 'equity')"
KINDS_AFTER = (
    "kind IN ('index', 'index_future', 'fx', 'rate', 'bond_future', 'commodity', 'equity', 'crypto')"
)

# 수집 중인 25종을 실제로 세어 보고 드러난 세 구멍을 메운다.
# (provider, symbol, kind, country, country_name, label)
#
# 1. 한국 정규장에 0봉인 심볼이 다섯이었다. 그중 `SOX`·`US10Y`에는 24시간 짝을
#    붙여 뒀는데 러셀만 없었다. `RUSSELL2000_FUT`가 그 짝이다.
# 2. 토 07:00 ~ 월 07:00 KST 48시간은 전 심볼이 0봉이었다. 그 구간에 움직이는 값은
#    암호화폐뿐이라 `crypto` kind를 여덟 번째로 연다.
# 3. 코스피는 현물·선물이 짝인데 코스닥은 현물뿐이었다. `KOSDAQ150_FUT`가 반쪽을 채운다.
#
# `DOW_FUT`는 구멍이 아니라 축을 넓히는 것이다. ES·NQ보다 가치·경기민감이 무거워
# 세 지수가 갈리는 날이 있다.
SEED: tuple[tuple[str, str, str, str, str, str], ...] = (
    ("kis", "KOSDAQ150_FUT", "index_future", "KR", "한국", "코스닥150 선물"),
    ("yahoo", "RUSSELL2000_FUT", "index_future", "US", "미국", "러셀2000 선물"),
    ("yahoo", "DOW_FUT", "index_future", "US", "미국", "다우 선물"),
    # 국가가 없는 자산이다. ISO 3166-1이 사용자 할당용으로 비워 둔 XA~XZ에서 XX를 쓴다.
    # `indicator_series`가 유로존에 XM을 쓰는 것과 같은 규칙이다.
    ("yahoo", "BTC", "crypto", "XX", "글로벌", "비트코인"),
    ("yahoo", "ETH", "crypto", "XX", "글로벌", "이더리움"),
)


def _reset_kind_check(definition: str) -> None:
    op.drop_constraint("ck_quote_symbol_kind", "quote_symbol", type_="check")
    op.create_check_constraint("ck_quote_symbol_kind", "quote_symbol", definition)


def upgrade_default() -> None:
    _reset_kind_check(KINDS_AFTER)
    op.alter_column(
        "quote_symbol",
        "kind",
        existing_type=sa.VARCHAR(length=20),
        existing_nullable=False,
        comment=KIND_COMMENT_AFTER,
        existing_comment=KIND_COMMENT_BEFORE,
    )

    for provider, symbol, kind, country, country_name, label in SEED:
        op.execute(
            sa.text(
                "INSERT INTO quote_symbol (provider, symbol, kind, country, country_name, label)"
                " VALUES (:provider, :symbol, :kind, :country, :country_name, :label)"
            ).bindparams(
                provider=provider,
                symbol=symbol,
                kind=kind,
                country=country,
                country_name=country_name,
                label=label,
            )
        )


def downgrade_default() -> None:
    for provider, symbol, *_ in SEED:
        op.execute(
            sa.text("DELETE FROM quote_bar WHERE provider = :provider AND symbol = :symbol").bindparams(
                provider=provider, symbol=symbol
            )
        )
        op.execute(
            sa.text("DELETE FROM quote_symbol WHERE provider = :provider AND symbol = :symbol").bindparams(
                provider=provider, symbol=symbol
            )
        )
    op.alter_column(
        "quote_symbol",
        "kind",
        existing_type=sa.VARCHAR(length=20),
        existing_nullable=False,
        comment=KIND_COMMENT_BEFORE,
        existing_comment=KIND_COMMENT_AFTER,
    )
    _reset_kind_check(KINDS_BEFORE)


def upgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market_migration() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
