"""add macro indicator kinds

Revision ID: fb3a83fe70f6
Revises: 2029012bafaa
Create Date: 2026-08-16 18:22:40.337858

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb3a83fe70f6"
down_revision: str | Sequence[str] | None = "2029012bafaa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# 새로 붙는 미국 월간 거시지표. 리비전에서 앱 코드를 import하지 않는다. import하면 나중에
# 수집기 Enum이 바뀔 때 과거 리비전의 결과가 따라 바뀐다. 대조는 tests/migrations가 한다.
#
# **만기가 NULL이다.** 물가지수와 소매판매에는 만기 개념이 없다. 0으로 채우면 만기별 비교
# 쿼리가 "0개월물"로 그린다.
#
# (provider, series_id, country, country_name, maturity_months, kind, label)
MACRO_SERIES_SEED: tuple[tuple[str, str, str, str, int | None, str, str], ...] = (
    ("fred", "CPI_M", "US", "미국", None, "price_index", "미국 소비자물가지수"),
    ("fred", "PPI_M", "US", "미국", None, "price_index", "미국 생산자물가지수(최종수요)"),
    ("fred", "RETAIL_SALES_M", "US", "미국", None, "activity", "미국 소매판매"),
)

# 지금 뷰는 `indicator_observation` 전체를 'rate'로 표시한다. 물가지수가 들어오면 그게 거짓이
# 되고, 조회하는 쪽이 지수에 금리 규칙(차분)을 적용해 퍼센트로 읽지 못한다. 마스터의 kind를
# 끌어온다. 마스터 행이 없는 계열도 남아야 해서 coalesce가 필요하다 — 관측값에서 마스터로
# 외래키를 걸지 않기 때문이다.
DAILY_SERIES_VIEW = """
CREATE OR REPLACE VIEW daily_series AS
SELECT provider, symbol AS series_id, business_date, close AS value, 'price' AS kind
FROM quote_daily
UNION ALL
SELECT o.provider, o.series_id, o.observation_date AS business_date, o.value,
       -- `CREATE OR REPLACE VIEW`는 컬럼 타입을 못 바꾼다. 마스터의 kind가 VARCHAR(20)이라
       -- 캐스트 없이 두면 기존 뷰의 text와 어긋나 교체가 거부된다.
       coalesce(s.kind::text, 'rate') AS kind
FROM indicator_observation o
LEFT JOIN indicator_series s ON s.provider = o.provider AND s.series_id = o.series_id
UNION ALL
SELECT provider, stock_code AS series_id, business_date, close_price AS value, 'price' AS kind
FROM stock_investor_trade_daily
UNION ALL
SELECT * FROM (
    SELECT DISTINCT ON (currency, date)
        'hana' AS provider, currency AS series_id, date AS business_date,
        exchange_standard_rate AS value, 'fx' AS kind
    FROM exchange_rate
    WHERE exchange_standard_rate > 0
    ORDER BY currency, date, round DESC
) AS hana_daily
"""

KIND_CHECK = "ck_indicator_series_kind"
MATURITY_CHECK = "ck_indicator_series_maturity_months"


def upgrade(engine_name: str) -> None:
    _run(f"upgrade_{engine_name}")


def downgrade(engine_name: str) -> None:
    _run(f"downgrade_{engine_name}")


def _run(name: str) -> None:
    # A revision written before an alias existed has no section for it, and
    # there is nothing for that alias to do. Adding an alias must not force a
    # no-op edit to every past revision.
    operations = globals().get(name)
    if operations is not None:
        operations()


def upgrade_default() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "indicator_series",
        "maturity_months",
        existing_type=sa.INTEGER(),
        nullable=True,
        comment="만기 개월 수. 만기별 비교와 정렬에 쓴다(3개월=3, 10년=120). 91일물은 3으로 둔다. 물가지수처럼 만기 개념이 없는 지표는 NULL이다",
        existing_comment="만기 개월 수. 만기별 비교와 정렬에 쓴다(3개월=3, 10년=120). 91일물은 3으로 둔다",
    )
    op.alter_column(
        "indicator_series",
        "kind",
        existing_type=sa.VARCHAR(length=20),
        comment="시계열의 종류(government_bond, money_market, price_index 또는 activity). 국채 곡선에서 단기 자금시장 금리를 가르고, 단위가 다른 거시지표를 그 곡선에서 뺀다",
        existing_comment="금리의 종류(government_bond 또는 money_market). 국채 곡선에서 단기 자금시장 금리를 가른다",
        existing_nullable=False,
    )
    op.create_table_comment(
        "indicator_series",
        "지표 시계열이 어느 나라 무슨 값인지 설명하는 마스터",
        existing_comment="지표 시계열이 어느 나라 무슨 금리인지 설명하는 마스터",
        schema=None,
    )
    # ### end Alembic commands ###

    # autogenerate는 CHECK 제약의 변경을 만들지 않는다. 손으로 갈아 끼운다.
    op.drop_constraint(KIND_CHECK, "indicator_series", type_="check")
    op.create_check_constraint(
        KIND_CHECK,
        "indicator_series",
        "kind IN ('government_bond', 'money_market', 'price_index', 'activity')",
    )
    op.drop_constraint(MATURITY_CHECK, "indicator_series", type_="check")
    op.create_check_constraint(
        MATURITY_CHECK,
        "indicator_series",
        "maturity_months IS NULL OR maturity_months > 0",
    )

    op.bulk_insert(
        sa.table(
            "indicator_series",
            sa.column("provider", sa.Text),
            sa.column("series_id", sa.Text),
            sa.column("country", sa.Text),
            sa.column("country_name", sa.Text),
            sa.column("maturity_months", sa.Integer),
            sa.column("kind", sa.String),
            sa.column("label", sa.Text),
        ),
        [
            dict(zip(("provider", "series_id", "country", "country_name", "maturity_months", "kind", "label"), row))
            for row in MACRO_SERIES_SEED
        ],
        # offline(`--sql`)에서는 executemany를 찍을 수 없다. 행마다 INSERT를 내게 한다.
        multiinsert=False,
    )

    op.execute(DAILY_SERIES_VIEW)


def downgrade_default() -> None:
    # 시드를 먼저 지운다. maturity_months가 NULL인 행이 남아 있으면 NOT NULL로 되돌릴 수 없다.
    tickers = ", ".join(f"'{row[1]}'" for row in MACRO_SERIES_SEED)
    op.execute(f"DELETE FROM indicator_series WHERE provider = 'fred' AND series_id IN ({tickers})")

    op.drop_constraint(MATURITY_CHECK, "indicator_series", type_="check")
    op.create_check_constraint(MATURITY_CHECK, "indicator_series", "maturity_months > 0")
    op.drop_constraint(KIND_CHECK, "indicator_series", type_="check")
    op.create_check_constraint(KIND_CHECK, "indicator_series", "kind IN ('government_bond', 'money_market')")

    # 뷰는 마스터를 조인하기 전으로 되돌린다.
    op.execute(
        """
        CREATE OR REPLACE VIEW daily_series AS
        SELECT provider, symbol AS series_id, business_date, close AS value, 'price' AS kind
        FROM quote_daily
        UNION ALL
        SELECT provider, series_id, observation_date AS business_date, value, 'rate' AS kind
        FROM indicator_observation
        UNION ALL
        SELECT provider, stock_code AS series_id, business_date, close_price AS value, 'price' AS kind
        FROM stock_investor_trade_daily
        UNION ALL
        SELECT * FROM (
            SELECT DISTINCT ON (currency, date)
                'hana' AS provider, currency AS series_id, date AS business_date,
                exchange_standard_rate AS value, 'fx' AS kind
            FROM exchange_rate
            WHERE exchange_standard_rate > 0
            ORDER BY currency, date, round DESC
        ) AS hana_daily
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "indicator_series",
        "지표 시계열이 어느 나라 무슨 금리인지 설명하는 마스터",
        existing_comment="지표 시계열이 어느 나라 무슨 값인지 설명하는 마스터",
        schema=None,
    )
    op.alter_column(
        "indicator_series",
        "kind",
        existing_type=sa.VARCHAR(length=20),
        comment="금리의 종류(government_bond 또는 money_market). 국채 곡선에서 단기 자금시장 금리를 가른다",
        existing_comment="시계열의 종류(government_bond, money_market, price_index 또는 activity). 국채 곡선에서 단기 자금시장 금리를 가르고, 단위가 다른 거시지표를 그 곡선에서 뺀다",
        existing_nullable=False,
    )
    op.alter_column(
        "indicator_series",
        "maturity_months",
        existing_type=sa.INTEGER(),
        nullable=False,
        comment="만기 개월 수. 만기별 비교와 정렬에 쓴다(3개월=3, 10년=120). 91일물은 3으로 둔다",
        existing_comment="만기 개월 수. 만기별 비교와 정렬에 쓴다(3개월=3, 10년=120). 91일물은 3으로 둔다. 물가지수처럼 만기 개념이 없는 지표는 NULL이다",
    )
    # ### end Alembic commands ###


def upgrade_finance() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_finance() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
